### PR TITLE
Add a script to check for version update

### PR DESCRIPTION
**Pull request by visionular**

### CODE REVIEW

**Comment by visionular** [comment]
@pengbins

**Comment by pengbins** [comment]
Maybe this can be done by Travis CI's [cron-jobs](https://docs.travis-ci.com/user/cron-jobs/)?

**Comment by visionular** [comment]
I think we need to manually test it before pushing. There may be unexpected changes causing the other script to break.

**Comment by pengbins** [comment]
Maybe the origin URL also does not need to expose?

**Pull request merged**
